Added Time Table Page
ADRE9/bunk-manager-mern pull request #118
Opened 2021-04-07 16:52 UTC by Artistic18

# Description:
1) Added Time Table Page.
2) Set redirects to the timetable page.
3) Created a separate reducer for timetable page to store all the states needed for the timetable page and to increase modularity.
4) Made all the necessary changes to make sure everything is working fine.

### Fixes #117 :

## Have you read the [Contributing Guidelines on Pull Requests](https://github.com/ADRE9/bunk-manager-mern/blob/master/contributing.md)?

- [x] Yes
- [ ] No

## Type of change:

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

## Screenshots:

2021-04-07 21:11 UTC, ADRE9 commented on client/src/components/pagesComponents/AuthHeader.js
> +            {props.tablePage?'': renderAdminTab()}
return null instead of ' '

2021-04-07 21:13 UTC, ADRE9 commented on client/src/actions/authActions.js
> +import { USER_LOADED, USER_LOADING, LOGIN_SUCCESS, AUTH_ERROR, LOGIN_FAIL, REGISTER_SUCCESS, REGISTER_FAIL, LOGOUT_SUCCESS, CLEAR_SUBJECTS, DELETING_USER, USER_DELETED,UPDATING_USER,USER_UPDATED, SET
create another file for this action since its already been a large file and moreover it has all the API calls integrated to it.

2021-04-07 21:15 UTC, ADRE9 requested changes
Its such an overkill it seems to make use of a global state to render the time table page. I would suggest a workaround please.

2021-04-07 22:27 UTC, Artistic18 commented
@ADRE9 global state is being used to disable the header on the timetable page. Even if it might work with passing a prop to the header file it would increase complexity. The table page is being rendered normally.

2021-04-07 22:44 UTC, ADRE9 commented
Can you show me the react profiling pic from your dev server.

2021-04-08 12:27 UTC, Artistic18 commented
@ADRE9 check discord.

2021-04-10 09:06 UTC, ADRE9 commented
@Artistic18 have you done the changes I've mentioned? And also resolve the conflicts.

2021-04-10 09:18 UTC, Artistic18 commented
@ADRE9 can you check discord please

2021-04-10 10:00 UTC, ADRE9 commented
make the PR to the timetable branch.

2021-04-10 12:41 UTC, Artistic18 commented
@ADRE9 done

2021-04-11 16:13 UTC, merged